---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM resources Github Actions pipeline deploy to AWS (ECR/ECS) over Github Actions OIDC provider for Watch'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Stack Parameters'
        Parameters:
          - Environment
Parameters:
  Environment:
    Description: 'Environment'
    Type: String
    AllowedValues: ['dev', 'qa', 'prod']
Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: 'sts.amazonaws.com'
              StringLike:
                token.actions.githubusercontent.com:sub: 'repo:aenetworks/aetn.watch.*'
      Policies:
        - PolicyName: 'GitHubActionsPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ecr:BatchGetImage'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:PutImage'
                  - 'ecr:UploadLayerPart'
                Resource:
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${Environment}-watch-*'
              - Effect: 'Allow'
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource:
                  - '*'
              - Effect: 'Allow'
                Action:
                  - 'ecs:RegisterTaskDefinition'
                  - 'ecs:DescribeTaskDefinition'
                Resource:
                  - !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${Environment}-watch-*'
              - Effect: 'Allow'
                Action:
                  - 'ecs:DescribeTaskDefinition'
                Resource:
                  - '*'
              - Effect: 'Allow'
                Action:
                  - 'iam:PassRole'
                Resource:
                  - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${Environment}-watch-*'
              - Effect: 'Allow'
                Action:
                  - 'ecs:UpdateService'
                  - 'ecs:DescribeServices'
                Resource:
                  - !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/${Environment}-watch-cluster-Cluster-*'
Outputs:
  TemplateID:
    Description: 'Template Id.'
    Value: 'base/iam-watch-github-actions-role.yaml'
  TemplateVersion:
    Description: 'Template Version.'
    Value: '__VERSION__'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  RoleArn:
    Value: !Ref Role
    Description: 'Role Arn'
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
