table redirects_301 {
    "/2016moments": "/16-moments-that-made-2016",
    "/2019lmcrules" : "/lmcrules",
    "/abby" : "/shows/dance-moms/playlist/abbys-favorite-episodes",
    "/americanprincess" : "/shows/american-princess",
    "/ask2besure": "/ask2bsure",
    "/ask2bsure": "/ask2bsure",
    "/asktobesure": "/ask2bsure",
    "/asktobsure": "/ask2bsure",
    "/astrology/love-compatibility/love-sex-astrology/zodiac-sign-compatibility" : "/",
    "/badguardian": "/the-bad-guardian-resources",
    "/battles" : "/shows/the-rap-game/playlist/best-battles",
    "/beautycon" : "/shows/glam-masters/pages/meet-the-cast-shop-the-winners-products-at-beautyconnyc",
    "/bingo" : "/its-a-wonderful-lifetime-bingo",
    "/blacklove" : "/shows/blacklove",
    "/bringit" : "/shows/bring-it",
    "/christmas" : "/christmas-movies",
    "/christmasmovies" : "/christmas-movies",
    "/conradandmichelleresources" : "/movies/conrad-and-michelle-if-words-could-kill/pages/conrad-michelle-resources",
    "/crazy" : "/shows/project-runway/playlist/craziest-unconventional-challenges",
    "/create" : "/profile/activate?source=TempPass",
    "/crime-of-a-lifetime-podcast": "/podcasts",
    "/dancemoms" : "/shows/dance-moms",
    "/dawn": "/shows/vc-andrews-dawn",
    "/deadlysecrets" : "/movies/deadly-secrets-by-the-lake",
    "/dianna" : "/shows/bring-it/playlist/dancing-dianna",
    "/dmquiz": "/dance-moms-superfan-quiz",
    "/email" : "/emails/sign-up",
    "/emails" : "/emails/sign-up",
    "/games": "/",
    "/geegeinterview" : "/shows/leave-it-to-geege/exclusives/geege-taylor-interview",
    "/glammasters": "/shows/glam-masters/articles/casting",
    "/herstory" : "/playlists/history-herstory",
    "/honeymoonislandsweeps" : "/shows/married-at-first-sight-honeymoon-island/pages/watch-and-win-sweepstakes",
    "/i-love-a-lifetime-movie": "/podcasts",
    "/its-a-wonderful-lifetime" : "/christmas-movies",
    "/itsawonderfullifetimebingo" : "/its-a-wonderful-lifetime-bingo",
    "/keyshiacole": "/movies/keyshia-cole-this-is-my-story",
    "/kfc" : "/movies/a-recipe-for-seduction",
    "/lifetime-movies": "/lmn",
    "/lifetime-movies/movies": "/lmn/movies",
    "/lifetime-movies/schedule": "/lmn/schedule",
    "/lifetime-movies/shows": "/lmn/shows",
    "/lifetime-movies/videos": "/lmn/videos",
    "/lifetime-movies/videos/movies": "/lmn/videos/movies",
    "/lifetime-tv-app" : "/apps",
    "/lifetime-tv-schedule": "/schedule",
    "/lifetimebookclubsweeps" : "/lifetime-book-club-sweeps",
    "/lifetimelessons" : "/playlists/lifetime-lessons",
    "/littlewomenatlanta" : "/shows/little-women-atlanta",
    "/lwatl" : "/shows/little-women-atlanta",
    "/lwatlanta" : "/shows/little-women-atlanta",
    "/lwla" : "/shows/little-women-la",
    "/mafs" : "/shows/married-at-first-sight",
    "/mafsaustralia" : "/shows/married-at-first-sight-australia",
    "/mafscasting": "/shows/married-at-first-sight/articles/mafs-casting",
    "/mafsemails" : "/emails/single/mafsemails",
    "/mafsrules" : "/shows/married-at-first-sight/pages/married-at-first-sight-relax-and-rekindle-sweepstakes-rules",
    "/mafswin" : "/shows/married-at-first-sight/pages/married-at-first-sight-relax-and-rekindle-sweepstakes",
    "/mahalia" : "/movies/robin-roberts-presents-mahalia",
    "/margarita" : "/movies/ill-be-home-for-national-margarita-day",
    "/marryingmillions" : "/shows/marrying-millions",
    "/maryj" : "/news/lifetime-movies-mary-j-blige",
    "/materialsshareterms" : "/ae-materials-share-terms",
    "/moments" : "/shows/married-at-first-sight/playlist/most-awkward-moments",
    "/monuments" : "/the-lifetime-herstory-map-a-guide-to-americas-statues-of-women",
    "/movies/24-to-life": "/shows/24-to-life",
    "/movies/a-christmas-melody" : "/movies/christmas-stars",
    "/movies/a-day-late-and-a-dollar-short/book-excerpt": "/movies/a-day-late-and-a-dollar-short/articles/book-excerpt",
    "/movies/a-doggone-christmas" : "/movies/christmas-unleashed",
    "/movies/a-sweet-christmas" : "/movies/a-sweet-christmas-romance",
    "/movies/aaliyah-the-princess-of-rnb/qa-with-alexandra-shipp": "/movies/aaliyah-the-princess-of-rnb/articles/qa-with-alexandra-shipp",
    "/movies/an-amish-murder/book-excerpt": "/movies/an-amish-murder/articles/book-excerpt",
    "/movies/anna-nicole/qa-with-agnes-bruckner": "/movies/anna-nicole/articles/qa-with-agnes-bruckner",
    "/movies/babies-behind-bars": "/shows/babies-behind-bars",
    "/movies/babysitters-black-book/avril-lavigne": "/movies/babysitters-black-book/articles/avril-lavigne",
    "/movies/betty-and-coretta/reflections-by-ilyasah-shabazz": "/movies/betty-and-coretta/articles/reflections-by-ilyasah-shabazz",
    "/movies/big-driver/script-snippet": "/movies/big-driver/articles/script-snippet",
    "/movies/big-driver/stephen-king": "/movies/big-driver/articles/stephen-king",
    "/movies/britney-ever-after/britney-ever-after-premieres-february-18-preview": "/movies/britney-ever-after/full-movie",
    "/movies/call-me-crazy-a-five-film/resources": "/movies/call-me-crazy-a-five-film/articles/resources",
    "/movies/campus-nightmares": "/lifetime-movies",
    "/movies/celebrity-ghost-stories": "/lifetime-movies",
    "/movies/cleveland-abduction/book-excerpt": "/movies/cleveland-abduction/articles/book-excerpt",
    "/movies/dark-angel": "/shows/v-c-andrews-heaven-series",
    "/movies/deadly-secrets-the-lost-children-of-dozier": "/specials/deadly-secrets-the-lost-children-of-dozier",
    "/movies/deadly-secrets-the-lost-children-of-dozier/video/deadly-secrets-the-lost-children-of-dozier": "/specials/deadly-secrets-the-lost-children-of-dozier/full-special",
    "/movies/drama": "/movies",
    "/movies/drew-peterson-untouchable/fatal-vows-the-tragic-wives-of-sergeant-drew-peterson-book-excerpt": "/movies/drew-peterson-untouchable/articles/fatal-vows-the-tragic-wives-of-sergeant-drew-peterson-book-excerpt",
    "/movies/drew-peterson-untouchable/joe-hosey-interview": "/movies/drew-peterson-untouchable/articles/joe-hosey-interview",
    "/movies/driven-to-murder/full-movie" : "/movies/the-bad-seed",
    "/movies/escaping-polygamy": "/shows/escaping-polygamy",
    "/movies/faith-under-fire-the-antoinette-tuff-story" : "/movies/faith-under-fire",
    "/movies/faith-under-fire-the-antoinette-tuff-story/about" : "/movies/faith-under-fire/about",
    "/movies/faith-under-fire-the-antoinette-tuff-story/faith-under-fire-the-antoinette-tuff-story-preview" : "/movies/faith-under-fire/faith-under-fire-preview",
    "/movies/fallen-hearts": "/shows/v-c-andrews-heaven-series",
    "/movies/footsteps-in-the-snow": "/specials/footsteps-in-the-snow",
    "/movies/gates-of-paradise": "/shows/v-c-andrews-heaven-series",
    "/movies/ghost-inside-my-child": "/lifetime-movies",
    "/movies/harry-and-meghan-a-royal-romance/harry-and-meghan-a-royal-romance-preview" : "/movies/harry-and-meghan-a-royal-romance",
    "/movies/heaven": "/shows/v-c-andrews-heaven-series",
    "/movies/holiday": "/movies",
    "/movies/i-dated-a-psycho": "/lifetime-movies",
    "/movies/i-escaped-my-killer": "/lifetime-movies",
    "/movies/i-killed-my-bff": "/shows/i-killed-my-bff",
    "/movies/i-love-you-but-i-lied": "/shows/i-love-you-but-i-lied",
    "/movies/i-survived": "/shows/i-survived",
    "/movies/i-survived-beyond-and-back": "/shows/i-survived-beyond-and-back",
    "/movies/i-was-possessed": "/lifetime-movies",
    "/movies/inspirational": "/movies",
    "/movies/intervention": "/shows/intervention",
    "/movies/intervention-codependent": "/shows/intervention-codependent",
    "/movies/killer-kids": "/shows/killer-kids",
    "/movies/killer-profile": "/lifetime-movies",
    "/movies/lifetime-movie-network": "/lifetime-movies",
    "/movies/lifetime-movie-network/watch-lmn-full-episodes": "/lifetime-movies/videos",
    "/movies/living-in-secret": "/lifetime-movies",
    "/movies/magical-christmas-shoes" : "/movies/the-magical-christmas-shoes",
    "/movies/monster-in-my-family": "/shows/monster-in-my-family",
    "/movies/mother-may-i-sleep-with-danger-original/top-5-mother-of-all-lifetime-movies": "/movies/mother-may-i-sleep-with-danger-original/articles/top-5-mother-of-all-lifetime-movies",
    "/movies/mother-may-i-sleep-with-danger/video/mother-may-i-sleep-with-danger-trailer": "/movies/mother-may-i-sleep-with-danger/mother-may-i-sleep-with-danger-trailer",
    "/movies/my-crazy-ex": "/shows/my-crazy-ex",
    "/movies/my-crazy-sex": "/shows/my-crazy-sex",
    "/movies/my-ghost-story": "/lifetime-movies",
    "/movies/my-ghost-story-caught-on-camera": "/shows/my-ghost-story-caught-on-camera",
    "/movies/my-haunted-house": "/shows/my-haunted-house",
    "/movies/my-uncle-is-the-green-river-killer": "/specials/my-uncle-is-the-green-river-killer",
    "/movies/nellie-bly" : "/movies/escaping-the-madhouse-the-nellie-bly-story",
    "/movies/nellie-bly/about" : "/movies/escaping-the-madhouse-the-nellie-bly-story/about",
    "/movies/nxivm-cult-a-mothers-nightmare" : "/movies/escaping-the-nxivm-cult-a-mothers-fight-to-save-her-daughter",
    "/movies/prosecuting-casey-anthony/exclusive-qa-with-jeff-ashton": "/movies/prosecuting-casey-anthony/articles/exclusive-qa-with-jeff-ashton",
    "/movies/prosecuting-casey-anthony/imperfect-justice-prosecuting-casey-anthony-book-excerpt": "/movies/prosecuting-casey-anthony/articles/imperfect-justice-prosecuting-casey-anthony-book-excerpt",
    "/movies/psychic-intervention": "/lifetime-movies",
    "/movies/reincarnated-past-lives": "/lifetime-movies",
    "/movies/romance": "/movies",
    "/movies/schedule": "/schedule",
    "/movies/steel-magnolias/diabetic-resources": "/movies/steel-magnolias/articles/diabetic-resources",
    "/movies/steel-magnolias/script-snippets": "/movies/steel-magnolias/articles/script-snippets",
    "/movies/story-of-a-girl/story-of-a-girl-preview": "/movies/story-of-a-girl",
    "/movies/strange-empire": "/lifetime-movies",
    "/movies/suspense": "/movies",
    "/movies/taken-from-me-the-tiffany-rubin-story/tiffany-rubin-interview": "/movies/taken-from-me-the-tiffany-rubin-story/articles/tiffany-rubin-interview",
    "/movies/tear-jerker": "/movies",
    "/movies/teen": "/movies",
    "/movies/the-cheerleader-murders/featured-music": "/movies/the-cheerleader-murders/articles/featured-music",
    "/movies/the-christmas-hotel" : "/movies/christmas-hotel",
    "/movies/the-craigslist-killer/date-with-death-book-excerpt": "/movies/the-craigslist-killer/articles/date-with-death-book-excerpt",
    "/movies/the-craigslist-killer/interview/date-with-death-author-michele-mcphee": "/movies/the-craigslist-killer/articles/date-with-death-author-michele-mcphee-interview",
    "/movies/the-gabby-douglas-story/outreach": "/movies/the-gabby-douglas-story/articles/outreach",
    "/movies/the-gabby-douglas-story/qa-with-gabby-douglas": "/movies/the-gabby-douglas-story/articles/qa-with-gabby-douglas",
    "/movies/the-haunting-of": "/shows/the-haunting-of",
    "/movies/the-last-goodbye": "/lifetime-movies",
    "/movies/the-pregnancy-project/gaby-rodriguez-interview": "/movies/the-pregnancy-project/articles/gaby-rodriguez-interview",
    "/movies/the-pregnancy-project/teen-pregnancy-resources": "/movies/the-pregnancy-project/articles/teen-pregnancy-resources",
    "/movies/the-pregnancy-project/the-pregnancy-project-book-excerpt": "/movies/the-pregnancy-project/articles/the-pregnancy-project-book-excerpt",
    "/movies/the-red-tent/anita-diamant": "/movies/the-red-tent/articles/anita-diamant",
    "/movies/the-secret-life-of-a-celebrity-surrogate" : "/movies/secret-life-of-a-celebrity-surrogate",
    "/movies/the-secret-life-of-marilyn-monroe/starlet-style": "/movies/the-secret-life-of-marilyn-monroe/articles/starlet-style",
    "/movies/the-secret-tapes-of-the-oj-case-the-untold-story": "/specials/the-secret-tapes-of-the-oj-case-the-untold-story",
    "/movies/the-secret-tapes-of-the-oj-case-the-untold-story/about": "/specials/the-secret-tapes-of-the-oj-case-the-untold-story",
    "/movies/the-secret-tapes-of-the-oj-case-the-untold-story/pictures": "/specials/the-secret-tapes-of-the-oj-case-the-untold-story/pictures",
    "/movies/the-simone-biles-story-courage-to-soar/the-simons-biles-story-courage-to-soar-preview" : "/movies/the-simone-biles-story-courage-to-soar/the-simone-biles-story-courage-to-soar-preview",
    "/movies/they-took-our-child-we-got-her-back": "/lifetime-movies",
    "/movies/those-who-kill": "/lifetime-movies",
    "/movies/true-crime": "/movies",
    "/movies/true-story": "/movies",
    "/movies/vc-andrews-all-that-glitters": "/shows/v-c-andrews-ruby-series",
    "/movies/vc-andrews-hidden-jewel": "/shows/v-c-andrews-ruby-series",
    "/movies/vc-andrews-pearl-in-the-mist": "/shows/v-c-andrews-ruby-series",
    "/movies/vc-andrews-ruby": "/shows/v-c-andrews-ruby-series",
    "/movies/web-of-dreams": "/shows/v-c-andrews-heaven-series",
    "/movies/william-and-kate/how-to-be-a-princess": "/movies/william-and-kate/articles/how-to-be-a-princess",
    "/movies/with-this-ring/relationship-tricks-and-tricks": "/movies/with-this-ring/articles/relationship-tricks-and-tricks",
    "/musicfactory" : "/shows/ms-ts-music-factory",
    "/mykillerbodycasting" : "/shows/my-killer-body-k-michelle/exclusives/casting-page",
    "/nwsl": "/shows/national-womens-soccer-league/pages/nwsl-live-stream",
    "/nwslpasstheball" : "/shows/national-womens-soccer-league/videos/nwsl-pass-the-ball-psa",
    "/nyfw": "/lifetime-at-nyfw/index.html",
    "/phroggingcasting" : "/shows/phrogging-hider-in-my-house/exclusives/phrogging-casting-page",
    "/popmusic": "/shows/the-pop-game/pages/music-guide",
    "/register": "/profile/activate",
    "/remakeitworkcontest": "/shows/project-runway/exclusives/remake-it-work-contest",
    "/ruby" : "/vc-andrews-ruby-movie-series",
    "/runwayexperience" : "/shows/project-runway/playlist/experience-the-runway",
    "/schedule.rss": "/schedule",
    "/schedule/lmn": "/lmn/schedule",
    "/schedule/lrw": "/lrw/schedule",
    "/schedule/ltv": "/schedule",
    "/sevendeadlysins" : "/playlists/seven-deadly-sins",
    "/shedidthat" : "/she-did-that",
    "/shopkins-sweeps" : "/shows/project-runway/pages/spot-your-shopkins-style-sweepstakes",
    "/shows/all-mixed-up": "/shows",
    "/shows/army-wives" : "/shows",
    "/shows/bama-state-style" : "/shows/",
    "/shows/baps" : "/shows/",
    "/shows/betty-whites-off-their-rockers" : "/shows/",
    "/shows/big-women-big-love" : "/shows/",
    "/shows/born-in-the-wild" : "/shows/",
    "/shows/bring-it/playlist/bring-it-season-3-curated-list": "/shows/bring-it/playlist/popular-full-dances",
    "/shows/celebrity-home-raiders" : "/shows/",
    "/shows/child-genius" : "/shows",
    "/shows/coming-home" : "/shows",
    "/shows/dance-moms/playlist/dance-moms-season-4-curated-list": "/shows/dance-moms/playlist/full-dances",
    "/shows/dance-moms/season-7/episode-0/abby-tells-all-special-preview": "/shows/dance-moms/season-7/episode-0",
    "/shows/dance-moms/season-7/episode-12/dance-moms-episode-12-preview": "/shows/dance-moms",
    "/shows/dance-moms/season-7/episode-25/dance-moms-episode-25-preview" : "/shows/dance-moms/season-7/episode-25",
    "/shows/dance-video-throwdown" : "/shows/",
    "/shows/date-night-live" : "/shows",
    "/shows/devious-maids/video/devious-maids-season-4-coming-in-june": "/shows/devious-maids/videos/devious-maids-season-4-first-look",
    "/shows/drop-dead-diva" : "/shows",
    "/shows/fempire-moments" : "/shows",
    "/shows/frasier" : "/shows/",
    "/shows/girlfriend-intervention" : "/shows/",
    "/shows/glam-masters/season-1/episode-8/glam-masters-episode-season-finale-preview" : "/shows/glam-masters/season-1/episode-8/glam-masters-season-finale-preview",
    "/shows/gold-medal-families" : "/shows/",
    "/shows/jump" : "/shows/",
    "/shows/life-flight-trauma-center-houston" : "/shows/",
    "/shows/little-women-dallas/season-2/episode-3/little-women-dallas-episode-3" : "/shows/little-women-dallas/season-2/episode-3",
    "/shows/little-women-la/season-6/episode-21/little-women-la-season-6-reunion": "/shows/little-women-la/season-6/episode-21",
    "/shows/little-women-la/season-6/episode-23/little-women-la-couples-retreat-preview": "/shows/little-women-la/season-6/episode-23",
    "/shows/livin-large" : "/shows",
    "/shows/living-with-the-enemy" : "/shows/",
    "/shows/married-at-first-sight-second-chances/season-1/episode-12/married-at": "/shows/married-at-first-sight-second-chances/season-1/episode-12",
    "/shows/married-at-first-sight/season-5/episode-17/married-at-first-sight-se" : "/shows/married-at-first-sight/season-5/episode-17",
    "/shows/married-at-first-sight/season-5/episode-17/married-at-first-sight-season-5-reunion-preview" : "/shows/married-at-first-sight/season-5/episode-17",
    "/shows/mary-kills-people/videos/mary-kills-people-preview": "/shows/mary-kills-people/season-1/episode-1/this-season-on-mary-kills-people",
    "/shows/million-dollar-shoppers" : "/shows",
    "/shows/mission-makeover": "/shows",
    "/shows/national-womens-soccer-league/pages/nwsl-live-stream2017": "/shows/national-womens-soccer-league/pages/nwsl-live-stream",
    "/shows/preach" : "/shows/",
    "/shows/pretty-wicked-moms" : "/shows",
    "/shows/prison-wives-club" : "/shows/",
    "/shows/project-runway-fashion-startup" : "/shows/",
    "/shows/project-runway-junior/season-2/episode-9/project-runway-junior-episo" : "/shows/project-runway-junior/season-2/episode-9",
    "/shows/project-runway-threads" : "/shows/",
    "/shows/project-runway/blog" : "/shows/project-runway",
    "/shows/project-runway/cast" : "/shows/project-runway",
    "/shows/project-runway/christopher-palus-blog" : "/shows/project-runway",
    "/shows/project-runway/designers": "/shows/project-runway/cast",
    "/shows/project-runway/exclusives/where-are-your-favorite-stars" : "/shows/project-runway",
    "/shows/project-runway/pages/blogs" : "/shows/project-runway",
    "/shows/project-runway/pages/recap-podcast" : "/shows/project-runway",
    "/shows/project-runway/pages/season-16-whos-in-whos-out" : "/shows/project-runway",
    "/shows/project-runway/pictures" : "/shows/project-runway",
    "/shows/project-runway/project-runway-blog" : "/shows/project-runway",
    "/shows/project-runway/season-16/episode-10/project-runway-episode-10-previe" : "/shows/project-runway/season-16/episode-10",
    "/shows/relative-insanity" : "/shows/",
    "/shows/shorts-on-time" : "/shows",
    "/shows/so-sharp/videos/so-sharp": "/shows/so-sharp",
    "/shows/so-sharp/videos/so-sharp-premieres-july-26-preview": "/shows/so-sharp/season-1/episode-1",
    "/shows/the-lizzie-borden-chronicles" : "/shows",
    "/shows/the-lottery" : "/shows",
    "/shows/the-motherdaughter-experiment-celebrity-edition" : "/shows",
    "/shows/the-new-adventures-of-old-christine" : "/shows/",
    "/shows/the-pop-game" : "/shows",
    "/shows/the-rap-game/season-3/episode-6/the-rap-game-episode-6-preview": "/shows/the-rap-game",
    "/shows/the-rap-game/season-3/episode-7/the-rap-game-episode-7-preview": "/shows/the-rap-game",
    "/shows/the-sisterhood-becoming-nuns" : "/shows/",
    "/shows/the-young-hillary-diaries": "/shows",
    "/shows/true-tori" : "/shows",
    "/shows/under-the-gunn" : "/shows/",
    "/shows/unsolved-mysteries" : "/shows",
    "/shows/vivicas-black-magic" : "/shows",
    "/shows/war-and-peace" : "/shows",
    "/shows/witches-of-east-end" : "/shows",
    "/somebodyschild" : "/movies/i-am-somebodys-child-the-regina-louise-story/pages/i-am-somebodys-child-resources",
    "/specials": "/shows",
    "/specials/beyond-the-headlines-britney-spears" : "/shows",
    "/specials/beyond-the-headlines-murder-in-the-family" : "/shows",
    "/specials/beyond-the-headlines-the-gabby-douglas-story" : "/shows",
    "/specials/billboard-women-in-music-2016" : "/shows",
    "/specials/biography-presents-michael-jackson" : "/shows",
    "/specials/biography-presents-simone-biles-american-gold" : "/shows",
    "/specials/breaking-their-silence-inside-the-gymnastics-scandal" : "/shows",
    "/specials/corey-feldman-moment-of-truth" : "/shows",
    "/specials/elizabeth-shoaf-the-girl-in-a-bunker" : "/shows",
    "/specials/griselda-the-godmother" : "/shows",
    "/specials/harry-and-meghan-the-royal-wedding" : "/shows",
    "/specials/jodi-arias-cellmate-secrets" : "/specials/jodi-arias-cell-mate-secrets",
    "/specials/michael-jackson-the-ultimate-icon" : "/shows",
    "/stopbreastcancer" : "/stop-breast-cancer-for-life",
    "/stopbreastcancerforlife" : "/stop-breast-cancer-for-life",
    "/stopviolenceagainstwomen" : "/stop-violence-against-women",
    "/survivingrkelly" : "/shows/surviving-r-kelly",
    "/the-table-is-ours": "/podcasts",
    "/thistimenextyear" : "/shows/this-time-next-year",
    "/top-10-lifetime-movies-based-on-a-true-story-you-must-watch" : "/20-lifetime-movies-based-on-true-stories",
    "/trappedresources" : "/movies/trapped-the-alex-cooper-story/pages/trapped-the-alex-cooper-story-resources",
    "/unrealsweeps" : "/shows/unreal/pages/ultimate-unreal-trivia-sweepstakes",
    "/upcoming-movies-its-a-wonderful-lifetime-2022" : "/christmas-movies",
    "/update": "/profile/information",
    "/vc-andrews-movies-and-series": "/vc-andrews-series",
    "/vcandrewswatchandwin" : "/vc-andrews-watch-and-win",
    "/veryvalentinesweeps" : "/very-valentine-sweeps",
    "/video": "/videos",
    "/videos/lifetimes-v-c-andrews-movies" : "/videos/lifetimes-v-c-andrews-movie-series-event",
    "/watch-full-episodes-online": "/videos",
    "/watch-full-movies-online": "/movies",
    "/whatmakesyourholidaywonderfulsweeps" : "/what-makes-your-holiday-wonderful-sweepstakes",
    "/wonderfullifetimesweepstakes" : "/its-a-wonderful-lifetime-sweepstakes",
    "/wrongbed": "/movies/the-wrong-bed-naked-pursuit"
}

table country_redirects_302 {
    "ar" : "https://lifetimeplay.tv/",
    "cl" : "https://lifetimeplay.tv/",
    "py" : "https://lifetimeplay.tv/",
    "uy" : "https://lifetimeplay.tv/",
    "bo" : "https://lifetimeplay.tv/",
    "ve" : "https://lifetimeplay.tv/",
    "do" : "https://lifetimeplay.tv/",
    "pe" : "https://lifetimeplay.tv/",
    "co" : "https://lifetimeplay.tv/",
    "ec" : "https://lifetimeplay.tv/",
    "hn" : "https://lifetimeplay.tv/",
    "pa" : "https://lifetimeplay.tv/",
    "mx" : "https://lifetimeplay.tv/",
    "cr" : "https://lifetimeplay.tv/",
    "sv" : "https://lifetimeplay.tv/",
    "ni" : "https://lifetimeplay.tv/",
    "gt" : "https://lifetimeplay.tv/",
    "br" : "https://lifetimeplay.tv/",
    "ca" : "https://mylifetimetv.ca/"
}

table eu_country_redirects_302 {
  "AT" : "https://www.aenetworks.tv/",
  "BE" : "https://www.aenetworks.tv/",
  "BG" : "https://www.aenetworks.tv/",
  "HR" : "https://www.aenetworks.tv/",
  "CY" : "https://www.aenetworks.tv/",
  "CZ" : "https://www.aenetworks.tv/",
  "DK" : "https://www.aenetworks.tv/",
  "EE" : "https://www.aenetworks.tv/",
  "FI" : "https://www.aenetworks.tv/",
  "FR" : "https://www.aenetworks.tv/",
  "DE" : "https://www.aenetworks.tv/",
  "GR" : "https://www.aenetworks.tv/",
  "HU" : "https://www.aenetworks.tv/",
  "IE" : "https://www.lifetimetv.co.uk/",
  "IT" : "https://www.aenetworks.tv/",
  "LV" : "https://www.aenetworks.tv/",
  "LT" : "https://www.aenetworks.tv/",
  "LU" : "https://www.aenetworks.tv/",
  "MT" : "https://www.aenetworks.tv/",
  "NL" : "https://www.aenetworks.tv/",
  "PL" : "https://www.lifetimetv.pl/",
  "PT" : "https://www.aenetworks.tv/",
  "RO" : "https://www.aenetworks.tv/",
  "SK" : "https://www.aenetworks.tv/",
  "SI" : "https://www.aenetworks.tv/",
  "ES" : "https://www.aenetworks.tv/",
  "SE" : "https://www.aenetworks.tv/",
  "GB" : "https://www.lifetimetv.co.uk/"
}
